ports:
    - port: 3000
tasks:
    - init: >
        export PIPENV_VENV_IN_PROJECT=true;
        pipenv shell;
        pipenv install;
        export FLASK_APP=src/main.py;
        export FLASK_ENV=development
      command: >
        pipenv shell;
        flask run -p 3000
