ports:
    - port: 3000
tasks:
    - init: >
        pip3 install -r requirements.txt;
        export FLASK_APP=src/main.py;
        export FLASK_ENV=development;
      command: >
        pipenv shell;
        flask run -p 3000
